spring:
  h2:
    console:
      enabled: true
      path: /console
      settings:
        web-allow-others: true
        trace: false
  datasource:
    name: dataSource
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: test
#    password: 123456
    schema:
      - classpath:sql/init.sql
    data:
      - classpath:sql/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming_strategy:  org.hibernate.cfg.ImprovedNamingStrategy
    database-platform: org.hibernate.dialect.H2Dialect